pipeline {
    agent {
        docker {
            image 'python:3.11-slim'
            args '-u root'  // Runs the container as root so we can install packages
        }
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    // Install Git if it's not available
                    sh 'apt-get update && apt-get install -y git'
                }
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    // Install pip requirements
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    // Run tests
                    sh 'pytest tests/'
                }
            }
        }
    }
}

